### ISSUE TITLE
リンク先を直す ✒

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/polymer-project.org-docs-jp#1]
リンク先がダイレクトな GAE になっているところを polymer-jp.org に直したい 💭 

https://lit-element-dot-polymer-japan.appspot.com/ 👉 https://lit-element.polymer-jp.org
https://pwa-starter-kit-dot-polymer-japan.appspot.com/ 👉 https://pwa-starter-kit.polymer-jp.org

**Comment by howking** [comment]
修正済み(cab9d54acb887fcc9891312b9470550669ce3f13)ですー
